services:
  api:
    container_name: api
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: dev
    networks:
      - web_network

  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
